# Generated by Django 4.2.30 on 2026-09-17 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repository_name', models.CharField(max_length=255)),
                ('repository_url', models.URLField()),
                ('language', models.CharField(blank=True, max_length=100, null=True)),
                ('stars', models.IntegerField(default=0)),
                ('forks', models.IntegerField(default=0)),
                ('open_issues', models.IntegerField(default=0)),
                ('total_commits', models.IntegerField(default=0)),
                ('contributors', models.IntegerField(default=0)),
                ('total_files', models.IntegerField(default=0)),
                ('total_directories', models.IntegerField(default=0)),
                ('repository_data', models.JSONField(default=dict)),
                ('commit_data', models.JSONField(default=dict)),
                ('file_data', models.JSONField(default=dict)),
                ('risk_data', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
